Repository terraform-redhat/terraform-rhcs-rosa-classic, pull requests merged in 2024-03, with the labels that each got.

#55 OCM-6406: shared vpc resources name_prefix changes
  examples/rosa-classic-public-with-shared-vpc/main.tf
  modules/shared-vpc-policy-and-hosted-zone/README.md
  modules/shared-vpc-policy-and-hosted-zone/main.tf
  modules/shared-vpc-policy-and-hosted-zone/variables.tf
Labels: approved, lgtm, jira/valid-reference

#57 OCM-6402: Use AWS partition variable instead of hardcoded "aws"
  README.md
  examples/rosa-classic-public-with-shared-vpc/README.md
  examples/rosa-classic-public-with-shared-vpc/main.tf
  main.tf
  modules/account-iam-resources/README.md
  modules/account-iam-resources/main.tf
  modules/oidc-config-and-provider/README.md
  modules/oidc-config-and-provider/main.tf
  modules/operator-roles/README.md
  modules/operator-roles/main.tf
  modules/rosa-cluster-classic/README.md
  modules/rosa-cluster-classic/main.tf
  modules/shared-vpc-policy-and-hosted-zone/README.md
  modules/shared-vpc-policy-and-hosted-zone/main.tf
Labels: approved, lgtm, jira/valid-reference

#56 OCM-6434: Fix rosa_classic_cluster sub-module
  modules/rosa-cluster-classic/main.tf
Labels: approved, lgtm, jira/valid-reference

#58 OCM-6428: examples - decouple the relationship between replicas and availability zones count
  Makefile
  examples/rosa-classic-public-with-byo-vpc-byo-iam-byo-oidc/main.tf
  examples/rosa-classic-public-with-shared-vpc/main.tf
  modules/oidc-config-and-provider/README.md
  scripts/verify-gen.sh
Labels: approved, lgtm, jira/valid-reference

#59 OCM-4999: Fix availability zones description
  modules/vpc/README.md
  modules/vpc/variables.tf
Labels: approved, lgtm, jira/valid-reference

#62 Add terraform-docs to the Dockerfile
  Dockerfile
  Makefile
Labels: approved, lgtm

#64 verify-gen: Ignore any change in Dockerfile
  scripts/verify-gen.sh
Labels: approved, lgtm

#65 verify-gen: Ignore any change in Dockerfile
  scripts/verify-gen.sh
Labels: approved, lgtm

#66 Remove sensitive info from "run-example.sh" log
  scripts/run-example.sh
Labels: approved, lgtm

#70 Remove Not Supported Alpha Version Notice
  README.md
Labels: approved, lgtm

#61 OCM-3300: edits to main readme file
  README.md
  modules/account-iam-resources/README.md
  modules/account-iam-resources/variables.tf
  modules/idp/README.md
  modules/idp/variables.tf
  modules/machine-pool/README.md
  modules/machine-pool/variables.tf
  modules/oidc-config-and-provider/README.md
  modules/oidc-config-and-provider/variables.tf
  modules/operator-policies/README.md
  modules/operator-policies/variables.tf
  modules/operator-roles/README.md
  modules/operator-roles/variables.tf
  modules/rosa-cluster-classic/README.md
  modules/rosa-cluster-classic/variables.tf
  modules/shared-vpc-policy-and-hosted-zone/README.md
  modules/shared-vpc-policy-and-hosted-zone/variables.tf
  modules/vpc/README.md
  modules/vpc/variables.tf
  variables.tf
Labels: ok-to-test, approved, lgtm, jira/valid-reference

#69 OCM-3300: Edits to examples readme files
  examples/rosa-classic-private-with-autoscaler-unmanaged-oidc-byo-vpc/README.md
  examples/rosa-classic-private-with-autoscaler-unmanaged-oidc-byo-vpc/variables.tf
  examples/rosa-classic-public-with-byo-vpc-byo-iam-byo-oidc/README.md
  examples/rosa-classic-public-with-byo-vpc-byo-iam-byo-oidc/variables.tf
  examples/rosa-classic-public-with-byo-vpc/README.md
  examples/rosa-classic-public-with-byo-vpc/variables.tf
  examples/rosa-classic-public-with-idp-machine-pools/README.md
  examples/rosa-classic-public-with-idp-machine-pools/variables.tf
  examples/rosa-classic-public-with-multiple-machinepools-and-idps/README.md
  examples/rosa-classic-public-with-multiple-machinepools-and-idps/variables.tf
  examples/rosa-classic-public-with-shared-vpc/README.md
  examples/rosa-classic-public-with-shared-vpc/variables.tf
  examples/rosa-classic-public-with-unmanaged-oidc/README.md
  examples/rosa-classic-public-with-unmanaged-oidc/variables.tf
  examples/rosa-classic-public/README.md
  examples/rosa-classic-public/variables.tf
Labels: ok-to-test, approved, lgtm, jira/valid-reference
